app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app_articles:
    resource: "@AppBundle/Controller/ArticleController.php"
    type: rest
